### ISSUE TITLE
Failed at the puppeteer@4.0.1 install script.

### ISSUE THREAD

**Issue by chiukit** [ahmetcetin/google-image-downloader#4]
1. Install with sudo
```
sudo npm install -g @ahmetcetin/image-downloader
```

Error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@4.0.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

npm 6.14.5
node v12.16.3

**Comment by ahmetcetin** [comment]
did you try to install without sudo? just tried again now, and it installs and works properly. The error message shows there is an error installing puppeteer 4.0.1, but this app requires puppeteer v5. Issue might be related with old version of puppeteer is installed already.Can you try to remove previous installation of puppeteer and try again?

**Comment by chiukit** [comment]
I tried to use with `-g` and use clone to execute the `bin/googledl`, then the problem resolved. This project is very useful. If the limit can be higher. It would be better. Thanks!
